[default]
phrasenode_train = "./one_shot_ipa/datasets/phrasenode/train.jsonl"
phrasenode_test = "./one_shot_ipa/datasets/phrasenode/test.jsonl"
phrasenode_dev = "./one_shot_ipa/datasets/phrasenode/dev.jsonl"
phrasenode_pages = "./one_shot_ipa/datasets/phrasenode/pages/"
[test]
phrasenode_dataset = "./tests/sample_data/example_file.txt"
phrasenode_sample = "./tests/datasets/phrasenode/sample.jsonl"
phrasenode_pages = "./tests/datasets/phrasenode/pages/"